/* Mentor Model Playbook — structured enlistment of all 33 mentor models.
   window.MODELS feeds the "Model Playbook" view (app.js renderModels).
   Sourced from education/mentors/data/<id>.js section-5 + docs/mentor_setup_catalog.md.
   verdict codes reuse window.EDU.verdicts (g/s/a/r/w); g stays empty. NO fabrication —
   fields not in the corpus = "not covered in corpus". */

window.MODELS = [

  // ─── TTrades (4) ───────────────────────────────────────────────────────────

  { id:"ttrades-c2-reversal", mentor:"TTrades", mentorKey:"ttrades", guideId:"ttrades",
    name:"Fractal Model C2 Reversal (TTFM)",
    session:"NY AM killzone 08:30–11:00 ET", sessionKey:"ny-am",
    htf:"Price reaches an HTF POI (old high/low, PDH/PDL, weekly extreme, or HTF FVG); daily candle sweeps C1's extreme into a higher-timeframe point of interest",
    trigger:"HTF candle sweeps C1's extreme but fails to displace, closing back inside C1's range; a CISD on the structural TF (e.g. 1H) confirms — a candle closes through the opening price of the opposing order block that drove price to the extreme",
    entry:"Drop to execution TF (5m/15m); enter on the CISD-confirming close or on a slight retest of that block",
    stop:"At the absolute swing extreme — the newly confirmed protected high/low",
    target:"Equilibrium of the HTF range, the opposing PDH/PDL, or a 2R minimum",
    tfs:"Daily bias → 1H structure → 5m/15m execution",
    tools:["C1/C2/C3 fractal","CISD","protected swing","PDH/PDL","T-Spot"],
    verdict:"a",
    example:"Daily candle sweeps the PDL into an HTF FVG and closes back inside the prior day's range (C2 closure, small wick); 1H CISD confirms; 5m entry on the retest targets the PDH.",
    donts:["Skip if a major HTF objective was just hit — no room left for expansion","Never force an entry when the trigger forms sluggishly or turns into consolidation","Don't move stop to break-even prematurely — invalidation is at the protected-swing extreme, not at entry","A continuation trigger forming exactly when a short-term target is swept = skip"] },

  { id:"ttrades-ic-cisd", mentor:"TTrades", mentorKey:"ttrades", guideId:"ttrades",
    name:"IC-CISD (Intracandle CISD)",
    session:"At 4H/1H candle opens (10:00 AM & 2:00 PM ET macros)", sessionKey:"htf-open",
    htf:"Confirmed HTF bias set by a prior C2/C3 closure; anticipating an expansion continuation day (C3/C4)",
    trigger:"Inside the developing HTF candle the LTF trends the wrong way to form the wick, dropping into the T-Spot; the IC-CISD is the LTF shifting back into trend by closing through the opposing order block — locking the HTF wick",
    entry:"On the close that validates the continuation order block, or a slight retest",
    stop:"Tucked tightly behind the new protected swing",
    target:"HTF external liquidity (old highs/lows) or a 2R minimum",
    tfs:"Daily/4H bias → 5m/15m execution",
    tools:["IC-CISD","protected swing","T-Spot","order block","C3/C4 continuation"],
    verdict:"a",
    example:"Daily C2 bullish closure locks direction; inside the new 4H candle price dips to the T-Spot, prints a 15m IC-CISD (closes through the down-close OB), locking the wick; entry targets the PDH.",
    donts:["Don't overcomplicate with dozens of PD arrays — analysis paralysis kills the IC-CISD read","Skip if the HTF candle's LTF trend is sluggish / forms consolidation instead of a clean wick","Never enter before the LTF closes back through the opposing order block — wait for the close","Avoid if a major HTF target was hit during this candle (no room to expand)"] },

  { id:"ttrades-unicorn", mentor:"TTrades", mentorKey:"ttrades", guideId:"ttrades",
    name:"Unicorn (Breaker + FVG)",
    session:"NY AM killzone 09:30–11:00 ET (high-volatility open)", sessionKey:"ny-am",
    htf:"Typically after price taps an HTF POI; high-volatility killzone (e.g. the 9:30 NY open)",
    trigger:"A structural stop hunt (e.g. High, Low, Higher High) then an aggressive displacement that shifts structure (Lower Low) — slicing cleanly through the last opposite-colored candle (the breaker) and leaving an FVG precisely overlapping it",
    entry:"At the overlapping zone — a blind limit at the start of the breaker, or a deeper retrace into the FVG for better R:R",
    stop:"Just beyond the breaker/FVG overlap, or at the absolute swing extreme",
    target:"A fixed 2R, or HTF external liquidity (session highs/lows)",
    tfs:"HTF context → 5m execution",
    tools:["breaker block","FVG","liquidity sweep","stop hunt","displacement"],
    verdict:"a",
    example:"9:30 spike sweeps the pre-market high (stop hunt), aggressively displaces down through the last up-close candle (breaker), leaving a bearish FVG inside it; limit short at the breaker start targets 2R.",
    donts:["Never anticipate expansion on a reversal candle with a large opposing wick — range and time already exhausted","Don't blindly catch the wick; wait for the wick to form and trade the continuation body","Skip if the breaker and FVG don't cleanly overlap — the edge requires the precise coincidence","Avoid if SMT divergence is present without a valid structural displacement to back it up"] },

  { id:"ttrades-ttfm-continuation", mentor:"TTrades", mentorKey:"ttrades", guideId:"ttrades",
    name:"TTFM Continuation (Candle 3/4)",
    session:"London + NY continuation (bias set prior day)", sessionKey:"london",
    htf:"Bias locked by a prior C2/C3 closure; trading strictly with trend momentum on an anticipated one-sided expansion day",
    trigger:"Price makes a shallow retrace into a POI (an FVG or short-term liquidity sweep), then aggressively displaces back into trend, closing through the opposing order block to validate a new protected swing",
    entry:"On the protected-swing-confirming close, or a slight retest of the validated continuation order block",
    stop:"On the new protected swing extreme",
    target:"HTF objectives, PDH/PDL, or SD projections (−2 to −2.5 SD); a 2R minimum applies",
    tfs:"Daily C3/C4 → 4H C3 → 15m protected swing (all three aligned)",
    tools:["C3/C4 continuation","CISD","protected swing","PDH/PDL","SD projection"],
    verdict:"a",
    example:"Daily C3 bullish expansion day; 4H C3 aligned; 15m price retraces to an FVG in the lower half, displaces through the down-close OB (protected swing), targets the PDH.",
    donts:["Skip if the retracement is deep — true C3 expansion has shallow pullbacks, a deep OTE retrace is an invalidation signal","Stay out of the internal chop of a 'Seek & Destroy' consolidation (no clean C3 profile)","Don't chase continuation if all three TF frames (Daily/4H/15m) are not aligned on C3/C4","Avoid if a continuation trigger prints exactly when a short-term HTF target is swept"] },

  // ─── Daye (4) ──────────────────────────────────────────────────────────────

  { id:"daye-q1-asian-sr", mentor:"Daye", mentorKey:"daye", guideId:"daye",
    name:"Q1 Asian Dynamic S/R",
    session:"Asian session Q1 06:00 PM – 12:00 AM ET", sessionKey:"asia",
    htf:"Q1 sets the daily barometer — the Asian range defines the dealing range that London (Q2) will manipulate and NY (Q3) will expand from; bias requires the cycle to be in a clear directional premium or discount with room to the opposing external liquidity",
    trigger:"Divide Q1 into thirds, let T1 pass; price pulls back into the Q1 opening price/gap during T2 or T3",
    entry:"Where the Q1 opening gap overlaps a fair value gap — a highly reactive dynamic S/R",
    stop:"Below the swing low that taps the Q1 opening gap",
    target:"Project 1 standard deviation from the T2–T3 defined range to forecast the session high/low",
    tfs:"Daily context → 15m execution",
    tools:["True Open","Quarterly Theory","FVG","Q1 defining range","SD projection"],
    verdict:"a",
    example:"Asia Q1 tight range; price dips into the 7:30 PM True Open overlapping a 15m FVG at T2; long targets 1 SD of the T2/T3 range.",
    donts:["Avoid Mondays — Q1 is the weekly barometer, choppy/low-prob (only tradeable with a major driver like NFP)","Skip if there is no confirmed directional premise in premium/discount (no room to the opposing external liquidity)","A LTF SMT that opposes the higher-timeframe cycle SMT is fake — don't trade it","Don't enter in T1; wait for the pullback to form in T2 or T3 before the setup qualifies"] },

  { id:"daye-q2-london-stophunt", mentor:"Daye", mentorKey:"daye", guideId:"daye",
    name:"Daily Q2 London Stop Hunt",
    session:"London session Q2 12:00 AM – 6:00 AM ET", sessionKey:"london",
    htf:"Q2 is the Judas Swing quarter — programmed to engineer a false directional move opposite the true daily bias; a valid setup requires the daily cycle to have a clear directional premise (premium or discount) so London's manipulation creates genuine trapped liquidity to fuel the Q3 expansion",
    trigger:"Price trades lower, sweeping the Asian (Q1) lows to engineer sell-side liquidity, but forms Sequential SMT against a correlated asset",
    entry:"Only when price is physically below the True Day Open (12:00 AM) AND the London 90m True Open (1:30 AM), with an LTF FVG or precision swing point",
    stop:"Below the lowest wick of the London manipulation low",
    target:"The buy-side liquidity above the Asian highs",
    tfs:"Daily/4H bias → 15m structure → 5m execution",
    tools:["Judas Swing","Sequential SMT","Stacked True Opens","FVG","True Day Open","London True Open"],
    verdict:"a",
    example:"London sweeps Asia lows below the 1:30 AM True Open (which is below the 12:00 AM True Day Open = stacked discount); Sequential SMT forms (NQ lower low, ES fails); long on 5m FVG targets Asian buy-side.",
    donts:["Don't trade on Tuesday unless red-folder news is present — no driver = no valid Judas","A LTF SMT opposing the higher-timeframe cycle is fake — the HTF SMT calls the shots","Don't sell the very first high/low that creates the Sequential SMT — wait for the timed run-out","Skip if price is NOT below both the 12:00 AM True Day Open and 1:30 AM London True Open (stacking required)"] },

  { id:"daye-q3-sweet-spot", mentor:"Daye", mentorKey:"daye", guideId:"daye",
    name:"Q3-of-Q3 \"Sweet Spot\"",
    session:"9:00–10:30 AM ET (Q3 of NY 90m cycle)", sessionKey:"ny-am",
    htf:"The Q3-of-Q3 alignment means the macro daily cycle and the intraday 90-minute cycle are simultaneously in their distribution quarter — the highest-probability expansion window in Quarterly Theory; the daily bias must already be set (Q1 barometer + Q2 manipulation complete) so Q3 expands aggressively toward external liquidity",
    trigger:"After the 8:30 AM news manipulation, Sequential SMT forms between assets (e.g. NQ lower low, ES higher low) strictly within 9:00–10:30",
    entry:"On an FVG or order block forming right after the SMT; for longs this must happen below the 7:30 AM NY True Open",
    stop:"Anchor a fib from the manipulation swing high to low; place the stop at the 1 SD projection",
    target:"External range liquidity (old highs/lows) or the opposite side of the daily dealing range",
    tfs:"Daily cycle (15m) → 90-minute cycle (5m)",
    tools:["Sequential SMT","True Open","Quarterly Theory","FVG","SD stop","Q3-of-Q3 timing"],
    verdict:"a",
    example:"8:30 news spikes down; 9:15 NASDAQ makes a lower low below the 7:30 AM NY True Open while ES holds higher; Sequential SMT confirmed; long on 5m FVG targets external buy-side liquidity.",
    donts:["Skip on Wednesdays/Thursdays only — avoid if neither Q1 barometer nor a red-folder driver is present","An HTF setup is disqualified until confirmed by a newly forming LTF SMT — 'if there is no confirmation it will just fail'","Non-sequential SMT (wrong day, wrong quarter order) = engineered trap, not a real signal","Don't enter above the 7:30 AM NY True Open in a long setup — price must be in the structural discount"] },

  { id:"daye-q4-afternoon-reversal", mentor:"Daye", mentorKey:"daye", guideId:"daye",
    name:"Q4 Afternoon Reversal",
    session:"Afternoon session Q4 12:00 PM – 6:00 PM ET", sessionKey:"ny-pm",
    htf:"Afternoon session (12:00 PM–6:00 PM ET) = Q4, programmed for explosive reversals",
    trigger:"Q3 (NY) expands aggressively; into Q4 price trades above the 1:30 PM Revolving True Open but fails to break the Q3 high, while a correlated asset breaks its Q3 high",
    entry:"Short as price breaks back below the 1:30 PM Revolving True Open, ideally overlapping an imbalance or precision swing point",
    stop:"Just above the newly formed SMT swing high",
    target:"The initial swing low after the SMT, or the 50% equilibrium of the day's dealing range",
    tfs:"Daily cycle (15m) → 90-minute Q4 cycle (5m)",
    tools:["Revolving True Open","Sequential SMT","Q3/Q4 transition","FVG","Quarterly Theory"],
    verdict:"a",
    example:"NY Q3 expands bullishly; at 1:30 PM price breaks above the Revolving True Open but NQ makes a higher high while YM fails (Sequential SMT); short below the Revolving True Open targets the 50% day equilibrium.",
    donts:["Skip on Fridays — Friday is intentionally excluded (retrace day), only a TGIF reversal qualifies","A LTF SMT that opposes the higher-timeframe cycle SMT is fake — need the larger cycle to cancel it","Don't execute on the strong asset (the one breaking the old high/low) — trade the laggard","Skip if there is no confirmed Q3 expansion to reverse off — Q4 reversal requires a full Q3 expansion first"] },

  // ─── GxT (4) ───────────────────────────────────────────────────────────────

  { id:"gxt-6am-reversal", mentor:"GxT", mentorKey:"gxt", guideId:"gxt",
    name:"6:00 AM NY Reversal → 10:00 AM Continuation",
    session:"NY AM 06:00–10:00 ET (killzone 08:00–10:00)", sessionKey:"ny-am",
    htf:"The 6:00 AM 4H candle is the ideal reversal window (contains the 8:30 & 9:30 drivers); its job is to manipulate into a key level and set the day's true high/low, leaving 10:00 to expand",
    trigger:"The 6:00 candle prints a reversal swing point / V-shape CSD before 10:00",
    entry:"At/shortly after the 10:00 open — price retraces to form the wick, finding support at an opposing bulky candle, breaker, or FVG left by the 6:00 expansion",
    stop:"At the EQ of the previous 1H/4H range, or below the bulky opposing candle/gap supporting the 10:00 open",
    target:"Unestablished session highs, ERL, or the opposing daily draw",
    tfs:"4H profile → 1H/30m structure → 5m/3m execution",
    tools:["4H candle profiling","V-shape CSD","FVG","breaker","driver pairing","IRL/ERL"],
    verdict:"a",
    example:"6:00 AM 4H candle sweeps the overnight low with a V-shape CSD; at 10:00 open price retraces into the FVG left by the displacement; long targets the engineered equal highs (ERL).",
    donts:["If the 8:30/9:30 driver fails to reverse, that is invalidation to the whole profile — don't assume a random time will reverse the day","Never frame a reversal off close-proximity / low-resistance highs and lows (failure swings only)","A deep pullback to OTE is an invalidation — true expansion has shallow retracements","Skip if the 6:00 AM candle prints a large opposing wick (doesn't support expansion; adjust targets back to the daily open)"] },

  { id:"gxt-ny-am-vshape", mentor:"GxT", mentorKey:"gxt", guideId:"gxt",
    name:"NY AM V-Shape Reversal",
    session:"NY AM killzone 09:30–11:00 ET", sessionKey:"ny-am",
    htf:"Price engages a relevant HTF key level (hourly/4H FVG or a protected swing low) in NY AM",
    trigger:"Aggressive expansion into the level immediately followed by sharp expansion away — a distinct V-shape, confirmed by a CSD on the 1m/3m/5m",
    entry:"On the CSD closure, or on the immediate retrace into the new gap (the SMT fill) left by the V-shape",
    stop:"Tightly below the absolute extreme (the wick) of the V-shape manipulation",
    target:"Low-resistance failure swings on the opposing side, or the next ERL",
    tfs:"4H/1H context → 5m/3m/1m execution",
    tools:["V-shape CSD","FVG","SMT Fill","IRL/ERL","failure swings"],
    verdict:"s",
    example:"9:35 NQ V-shapes off the 4H FVG; 3m CSD confirms; entry on the SMT fill (YM hits the gap, NQ doesn't); targets the engineered equal highs.",
    donts:["A deep retracement to OTE is an invalidation — true expansion has shallow retracements; if you see one, don't enter","Skip if the candle prints a large opposing manipulation wick from the open — it doesn't support expansion","Never frame off close-proximity / low-resistance failure swings — the V-shape must tap a relevant HTF key level","Don't chase the first break or strong-asset extreme — enter the laggard or wait for the SMT fill"] },

  { id:"gxt-driver-pairing", mentor:"GxT", mentorKey:"gxt", guideId:"gxt",
    name:"Driver Pairing",
    session:"08:30 / 09:30 ET news drivers", sessionKey:"news",
    htf:"Approaching a high-volatility driver (8:30 news / 9:30 open); the setup depends on whether a reversal is already established",
    trigger:"If no daily high/low exists yet → the driver spikes into a key level, manipulates it, and creates the reversal; if a reversal is already in → the driver simply opens and expands away from the key level",
    entry:"A positional limit at a bulky opposing candle right before the driver (anticipating pure expansion), or immediately after the driver forms its 1m/3m V-shape CSD",
    stop:"Behind the order block or FVG the driver is expanding away from",
    target:"Unestablished session highs, PDH/PDL, or failure swings — drivers knife through low-resistance liquidity",
    tfs:"1H context → 1–5m execution",
    tools:["SMT divergence","CISD","news driver","liquidity sweep","V-shape CSD"],
    verdict:"r",
    example:"8:30 print spikes NQ into the PDH, NQ fails while ES makes a higher high (SMT), 1m CISD confirms the short.",
    donts:["If the driver fails to reverse, that invalidates the whole profile — don't assume a later random time will do the job","Never long the asset that creates the double sweep — long the asset with the double failure swing (extreme strength)","Skip if no clear V-shape CSD forms post-driver — a sluggish or consolidating move is not the setup","Large opposing wick from the open = doesn't support expansion; skip or adjust targets to the daily open"] },

  { id:"gxt-lagging-asset-smt", mentor:"GxT", mentorKey:"gxt", guideId:"gxt",
    name:"Lagging-Asset SMT (Asset Synchronization)",
    session:"NY AM / NY PM killzones", sessionKey:"ny-am",
    htf:"Viewing the correlated triad (NQ/ES/YM); the leading (strongest) asset hits the ERL draw first",
    trigger:"The leader fails to manipulate the high and consolidates/retraces slightly, while the lagging asset (not yet at the draw) forms a Strength Switch PSP — momentarily closing stronger (bullish) while the leader closes bearish",
    entry:"The lagging/weakest asset immediately after the strength-switch PSP closure or an SMT fill inside a gap",
    stop:"Below the low of the strength-switch PSP or the SMT gap",
    target:"The exact same high/low draw the leading asset already hit",
    tfs:"1H/4H context → 5m/3m execution",
    tools:["Strength Switch PSP","SMT Fill","IRL/ERL","SMT triad","Advanced Premium/Discount"],
    verdict:"r",
    example:"NQ sweeps the session high and consolidates; YM (lagging) prints a Strength Switch PSP (closes bullish while NQ bearish) inside a 15m FVG; long YM targets the same session high NQ swept.",
    donts:["Never long the asset that created the double sweep — only trade the lagging asset showing extreme strength via double failure swing","Deep retracement kills the lagging-asset expansion idea — if the lagging asset retraces deeply after the PSP, skip","Skip if the driver fails to establish the leading asset's reversal — no confirmed leader = no valid lag","Don't fight the higher timeframe — a lagging-asset SMT that opposes the HTF cycle direction is a trap"] },

  // ─── ICT (4) ───────────────────────────────────────────────────────────────

  { id:"ict-ny-am-ote", mentor:"ICT", mentorKey:"ict", guideId:"ict",
    name:"NY AM V-Shape / Optimal Trade Entry (OTE)",
    session:"NY AM killzone 09:30–11:00 ET", sessionKey:"ny-am",
    htf:"Daily/4H bias set; price into a HTF PD array in the draw direction",
    trigger:"Early-session liquidity raid → MSS/displacement breaks structure",
    entry:"62–79% OTE retrace (70.5% sweet spot) into the 1st-presented FVG/OB",
    stop:"Beyond the swing extreme (0% of the OTE leg)",
    target:"First opposing swing / −0.5/−1/−1.5 SD projection",
    tfs:"Daily/4H bias → 5m/1m execution",
    tools:["liquidity sweep","MSS","displacement","FVG","OTE (Fibonacci)"],
    verdict:"s",
    example:"NQ sweeps the Asia low at 09:35, displaces up through structure, retraces to the 70.5% OTE + FVG, runs to the first opposing swing.",
    donts:["Daily/4H limit and stop-order models are not valid while the candle is still forming — wait for the close","'When it's not obvious assume it's not there' — if the SMT divergence isn't undeniably clear, skip","Don't buy a move that has already gapped too far from its consolidation","Avoid selling daily/weekly premium arrays if the TF just posted a lower low and rejected (bullish breaker — it's invalidated)"] },

  { id:"ict-silver-bullet", mentor:"ICT", mentorKey:"ict", guideId:"ict",
    name:"Silver Bullet",
    session:"10:00–11:00 AM or 2:00–3:00 PM ET (algorithmically time-bound)", sessionKey:"ny-am",
    htf:"Time-based continuation strictly within the 10:00–11:00 AM or 2:00–3:00 PM ET hour; daily bias confirmed",
    trigger:"A displacement swing that leaves an FVG within that 60-minute window",
    entry:"A limit as price retraces into the FVG, targeting the gap extreme or its consequent encroachment (midpoint)",
    stop:"Beyond the local swing extreme that preceded the displacement gap",
    target:"Opposing session liquidity, or standard deviations mapped from the 30-minute opening range",
    tfs:"Daily bias → 5m/1m execution within the timed window",
    tools:["FVG","Silver Bullet window","consequent encroachment","displacement","SD projection"],
    verdict:"a",
    example:"10:05 displacement leaves a bearish 5m FVG; price retraces to the FVG consequent encroachment at 10:20 inside the Silver Bullet hour; short targets opposing session liquidity.",
    donts:["Not valid outside the 10:00–11:00 AM or 2:00–3:00 PM ET windows — time is the non-negotiable gate","Daily limit/stop-order models are not valid while the candle is still forming — wait for the bar close","'When it's not obvious assume it's not there' — unclear SMT or displacement = skip","Don't buy a move that has already gapped too far from its consolidation base"] },

  { id:"ict-judas-turtle-soup", mentor:"ICT", mentorKey:"ict", guideId:"ict",
    name:"Judas Swing / Turtle Soup",
    session:"NY open Judas 09:30 ET (also London open 02:00–05:00 ET)", sessionKey:"ny-am",
    htf:"The manipulation phase of the daily Power of 3, launching in the NY or London open",
    trigger:"Price drives opposite the true bias, running 10/20/30 points above an old high (BSL) or below an old low (SSL) to trap breakout traders",
    entry:"Immediate execution into the stop hunt as it sweeps external liquidity — stepping in as retail stops trigger",
    stop:"Above the highest sweep wick (shorts) / below the lowest sweep wick (longs)",
    target:"Price cycling back inside the range to opposing IRL (a discount FVG/OB) or the opposite side",
    tfs:"Daily/4H bias → 5m/1m execution",
    tools:["BSL/SSL","Judas Swing","Power of 3","liquidity sweep","FVG/OB","turtle soup"],
    verdict:"a",
    example:"9:30 bell: NQ spikes above pre-market BSL trapping breakout longs; wicks pierce the high but bodies close back inside the range; short entry as the stop hunt completes targets the discount FVG.",
    donts:["CBDR >40 pips (2:00–8:00 PM NY range) — move to the sidelines; ranges >30 pips 'tend to be unfruitful for projections'","'When it's not obvious assume it's not there' — if the liquidity sweep isn't clearly trapping retail stops, skip","Don't fight the higher timeframe — a Judas in the wrong HTF direction is a losing fade","Avoid selling daily/weekly premium arrays if the TF just posted a lower low and rejected (invalidated breaker)"] },

  { id:"ict-mss-fvg-2022", mentor:"ICT", mentorKey:"ict", guideId:"ict",
    name:"MSS + FVG Entry (the 2022 model)",
    session:"8:30–11:00 AM ET index macro window", sessionKey:"ny-am",
    htf:"5m→1m within an index macro (e.g. 8:30–11:00 AM ET); a clear liquidity raid on an old high/low must have just occurred",
    trigger:"Aggressive displacement reversing from the pool that causes a rapid MSS and leaves an FVG (at/above equilibrium for shorts; at/below for longs)",
    entry:"A limit at the anatomy of the 3-candle gap — the high of the discount low (shorts) / the low of the premium high (longs)",
    stop:"At the extreme of the 3-candle gap",
    target:"Ride the expansion from the entry PD array to an opposing PD-array objective (premium FVG → discount FVG / old session low)",
    tfs:"5m structure → 1m entry",
    tools:["MSS","FVG","liquidity raid","displacement","equilibrium","consequent encroachment"],
    verdict:"a",
    example:"8:35 liquidity raid sweeps the pre-market low; aggressive MSS prints a bearish 5m FVG above equilibrium; limit short at the FVG anatomy runs to the opposing discount FVG.",
    donts:["Not valid while the daily candle is still forming — wait for the bar close before framing limit/stop models","Don't buy a move that has already gapped too far from its consolidation base","'If there is no obvious indication they are moving large funds, pass on the trade' — unclear displacement = skip","Avoid if the FVG prints at/below equilibrium for shorts (or at/above for longs) — placement relative to EQ is the filter"] },

  // ─── Dexter (6) ────────────────────────────────────────────────────────────

  { id:"dexter-4h-po3", mentor:"Dexter", mentorKey:"dexter", guideId:"dexter",
    name:"4H Power-of-Three Expansion",
    session:"At 4H candle opens, NY-tradeable 10:00 AM & 2:00 PM ET", sessionKey:"htf-open",
    htf:"The open of a 4H candle mapping delivery from an origin HTF PD array (A) to an opposing HTF PD array (B)",
    trigger:"An accumulation range forms at the 4H open, manipulates above/below the open to reach the 2–2.5 STDV projection of that range, and forms an SMT divergence in the highs/lows",
    entry:"Entry 1 at the order block ending the manipulation; Entry 2 at the first FVG of the initial displacement; Entry 3 at internal liquidity inside the 1–1.5 STDV Silver Bullet Zone",
    stop:"Above/below the manipulation extreme or HTF-PD-array invalidation",
    target:"The 2–2.5 STDV level, with potential extension to 3.5–4 or an unbalanced 4H FVG",
    tfs:"4H/1H context → 15m/5m execution",
    tools:["Power of Three","standard deviation","SMT divergence","Silver Bullet Zone","order block","FVG"],
    verdict:"a",
    example:"10:00 AM 4H candle opens; price accumulates then manipulates below the open to 2–2.5 SD; SMT forms (NQ sweeps low, ES doesn't); entry on the OB ending manipulation targets the opposing 4H FVG at 2.5 SD.",
    donts:["Don't expect continuation past the 2–2.5 SD target unless there are unmitigated HTF targets above","A directional bias is invalidated once price fully closes beyond the opening price + its overlapping defensive structures (OB/FVG)","Once a candle body cleanly closes past the 4-deviation extreme, re-anchor the SD projection — current anchor is disqualified","Don't take a Smart-Money-Reversal at a 2.5 terminus if it opposes your macro HTF premise"] },

  { id:"dexter-mmxm", mentor:"Dexter", mentorKey:"dexter", guideId:"dexter",
    name:"Market Maker Buy/Sell Model (MMXM)",
    session:"Daily/Weekly/Monthly HTF PO3 delivery (mapped day-to-day)", sessionKey:"htf-open",
    htf:"HTF PO3 delivery (Daily/Weekly/Monthly) mapping a macro route from one HTF PD array to an opposing one",
    trigger:"Price reaches an HTF PD array exactly at the 2–2.5 or 3.5–4 terminus of the previous manipulation range and forms a Smart Money Reversal",
    entry:"The low-risk buy/sell at the 0–0.5 band (first OB/FVG), or re-accumulate at the 1–1.5 band on internal liquidity",
    stop:"Invalidation of the macro HTF PD array",
    target:"The opposing HTF PD array (Point B/C) and its terminus",
    tfs:"Weekly/Daily context → 4H/1H → 15m execution",
    tools:["MMXM","Power of Three","standard deviation","Smart Money Reversal","SMT divergence","Silver Bullet Zone"],
    verdict:"a",
    example:"Daily PO3 pushes from origin OB; at 2.5 SD terminus an SMT forms (NQ higher high, ES fails); SMR confirmed at 0–0.5 SD entry band; targets the opposing daily PD array.",
    donts:["Don't take a Smart-Money-Reversal at a 2.5 terminus if it opposes your macro HTF premise","Don't expect continuation past the 2–2.5 SD terminus unless there are unmitigated HTF targets beyond it","A directional bias is invalidated once price fully closes beyond the opening price + its overlapping defensive structures","Re-anchor the SD projection if a candle body cleanly closes past the 4-deviation extreme — old anchor is void"] },

  { id:"dexter-tuesday-reversal", mentor:"Dexter", mentorKey:"dexter", guideId:"dexter",
    name:"Tuesday Reversal Profile",
    session:"Tuesday 10:00 AM ET (30-minute PO3)", sessionKey:"dow",
    htf:"A weekly PO3 macro cycle specifically on a Tuesday; the weekly chart has aggressively expanded and reaches the 3.5–4 STDV terminus on Tuesday",
    trigger:"A lower-timeframe candle body shifts structure and closes back above/below a specific HTF time element (the Weekly Open or Monthly Open) at the 3.5–4 terminus — the intersection of the time element and the price terminus is the mechanical confirmation",
    entry:"Wait for a lower-timeframe candle body to shift structure and close back above/below a specific HTF time element (Weekly or monthly open)",
    stop:"Beyond the 3.5–4 terminus extreme",
    target:"The previous daily low/high, Monday's low, or a daily buy-/sell-side imbalance",
    tfs:"Weekly context → 4H/1H → 30m/5m execution",
    tools:["Tuesday Reversal Profile","Power of Three","standard deviation","SMT divergence","time element"],
    verdict:"a",
    example:"Weekly chart pushes to 3.5 SD by Tuesday; NQ sweeps weekly high but S&P fails (SMT); 30m candle body closes back below the July Monthly Open; short targets Monday's low.",
    donts:["Invalidated if price fails to respect the defensive array or time element — e.g. for a bearish continuation, invalidation = price back above the previous daily low","Don't expect continuation past the 2–2.5 SD target unless there are unmitigated HTF targets remaining","A directional bias is invalidated once price fully closes beyond the opening price + its overlapping defensive structures","Don't trade this profile on any day other than Tuesday — the time element is non-negotiable"] },

  { id:"dexter-news-nfp-jolts", mentor:"Dexter", mentorKey:"dexter", guideId:"dexter",
    name:"High-Impact News (NFP & JOLTS)",
    session:"NFP/Unemployment at 8:30 ET or JOLTS at 10:00–10:30 ET", sessionKey:"news",
    htf:"A driver-release window — NFP/Unemployment (8:30) or JOLTS (10:00); first 30 minutes is dedicated to engineering liquidity by trapping traders",
    trigger:"After the 30-minute liquidity-engineering window closes, a 5- or 15-minute candle body closes entirely outside the initial 30-minute range and beyond the exact news open price — that body close is the directional confirmation",
    entry:"Wait for price to close entirely outside the initial 30-minute range, then enter on a retracement to an FVG/inversion once a 5- or 15-minute body closes above/below the exact news open price",
    stop:"Invalidation of the news-range boundaries",
    target:"The HTF draw on liquidity or opposing external liquidity outside the engineered range",
    tfs:"HTF context → 15m/5m entry post-30m range break",
    tools:["news open price","FVG","inversion FVG","liquidity sweep","Power of Three","news driver"],
    verdict:"a",
    example:"JOLTS 10:00 AM; 10:00–10:30 sweeps both BSL and SSL; at 10:30 a 5m candle closes above the news open price; enter long on the retracement FVG; targets the HTF draw above.",
    donts:["Don't enter before the full 30-minute liquidity-engineering window closes — the first 30 minutes is solely for trapping traders","A directional bias is invalidated once price fully closes beyond the opening price + its overlapping defensive structures","Don't trade if the 5m/15m body does NOT close entirely outside the initial 30-minute range — that body close is the required confirmation","Skip if the macro HTF draw has already been reached — no extension targets left"] },

  { id:"dexter-silver-bullet-zone", mentor:"Dexter", mentorKey:"dexter", guideId:"dexter",
    name:"Silver Bullet Zone Continuation",
    session:"Intraday distribution phase of a developing PO3", sessionKey:"ny-am",
    htf:"The intraday distribution/expansion phase of a developing PO3; Smart Money Reversal already confirmed",
    trigger:"Price finishes manipulation, confirms a Smart Money Reversal, and reaches the 1–1.5 STDV level of the projected range",
    entry:"Exclusively on internal liquidity (FVG/OB) strictly within the 1–1.5 band; if no FVG exists, wait for a sweep of internal stops before continuing",
    stop:"Invalidation of the Silver Bullet FVG or accumulation level",
    target:"The 2–2.5 STDV terminus",
    tfs:"4H/1H context → 5m execution",
    tools:["Silver Bullet Zone","standard deviation","FVG","OB","Smart Money Reversal"],
    verdict:"a",
    example:"Smart Money Reversal confirmed at 0–0.5 SD; price expands then retraces to the 1–1.5 SD Silver Bullet Zone with a 5m FVG; entry targets the 2.5 SD terminus.",
    donts:["Only valid on internal liquidity (FVG/OB) strictly within the 1–1.5 SD band — entries outside that band are not this setup","If no FVG exists at the 1–1.5 band, wait for a sweep of internal stops before entering — don't force a blind limit","Don't expect continuation past the 2–2.5 SD terminus without unmitigated HTF targets","The SD anchor is disqualified if a candle body cleanly closes past the 4-deviation extreme — re-anchor before continuing"] },

  { id:"dexter-devils-mark", mentor:"Dexter", mentorKey:"dexter", guideId:"dexter",
    name:"Devil's Mark Reversal",
    session:"At a PO3 time opening (e.g. 6:00 AM ET)", sessionKey:"htf-open",
    htf:"A PO3 time opening (e.g. 6:00 AM) where a candle opens and immediately expands heavily without printing an initial wick",
    trigger:"The candle opens and explodes with massive velocity without printing an initial wick, reaching an HTF PD array or a 2–2.5 terminus",
    entry:"On the reversal displacement away from the terminus",
    stop:"Above/below the standard-deviation terminus level",
    target:"The exact opening price of the current candle (to print the missing wick)",
    tfs:"1H/4H context → 5m/15m execution",
    tools:["Devil's Mark","Power of Three","standard deviation","HTF PD array","SMT divergence"],
    verdict:"a",
    example:"6:00 AM: 4H candle opens and rockets up with no wick to the 2.5 SD terminus at a daily OB; SMT forms; entry on reversal displacement targets the 6:00 AM opening price.",
    donts:["Do NOT blindly buy a massive immediate breakout with NO initial wick — the no-wick open is the reversal signal, not a continuation entry","Don't take a Smart-Money-Reversal at a 2.5 terminus if it opposes your macro HTF premise","A directional bias is invalidated once price fully closes beyond the opening price + its overlapping defensive structures","Large opposing wick or deep retracement after the open = disqualified; the edge requires the extreme velocity with no initial wick"] },

  // ─── XYJ (6) ───────────────────────────────────────────────────────────────

  { id:"xyj-lathyrus-80", mentor:"XYJ", mentorKey:"xyj", guideId:"xyj",
    name:"The Lathyrus 80% Model (ERL↔IRL)",
    session:"NY AM killzone (9:30–11:00 ET, extends into 10:00)", sessionKey:"ny-am",
    htf:"Daily engages an ERL (PDH/PDL); the Hourly forms an internal retrace into a discount/premium IRL gap",
    trigger:"A 15m SMT between triad assets inside the hourly gap, paired immediately with a 15m Market Structure Shift (MSS)",
    entry:"On the retest of the newly created 15m FVG left by the MSS displacement",
    stop:"A candle-body closure through the first candle of the entry FVG",
    target:"The opposing IRL or an obvious opposing swing pool — typically 2R–2.5R",
    tfs:"Daily/1H context → 15m entry",
    tools:["IRL/ERL","SMT","MSS","FVG","Lathyrus 5-component","midnight open filter"],
    verdict:"r",
    example:"Daily PDL engaged; 1H retraces into an IRL gap below the midnight open; 15m SMT + MSS inside the gap; long on 15m FVG retest targets the opposing IRL at 2R.",
    donts:["Must be shorting ABOVE the midnight open and longing BELOW the NY open — wrong side of the daily open = disqualified","Reversals require a V-shaped displacement — if your CISD looks like consolidation, do not trade that fractal","Deep retracement kills expansion — if candle-3 extends far past equilibrium of candle-2, invalidate the expansion idea","Don't place gaps near the candle's high (premium) — gaps must form near the open, in the upper half of the expanding candle's range"] },

  { id:"xyj-2stage-cic", mentor:"XYJ", mentorKey:"xyj", guideId:"xyj",
    name:"The 2-Stage CiC True Reversal (Candle 2)",
    session:"NY AM killzone 09:30–11:00 ET", sessionKey:"ny-am",
    htf:"Price reaches a HTF key level (4H gap, Daily ERL) to order-pair and reverse to the opposing side",
    trigger:"The extreme validated strictly by a two-stage CiC (SMT confirming a PSP, PSP confirming an SMT, or a two-stage SMT)",
    entry:"Drop to 15m/5m/3m; wait for a V-shape displacement + CISD that leaves a fresh gap",
    stop:"At the true invalidation — the extreme wick of the reversal",
    target:"The opposing side of the HTF dealing range, or a static 2R",
    tfs:"4H/Daily context → 15m/5m/3m execution",
    tools:["2-stage CiC","PSP","SMT","CISD","V-shape","IRL/ERL"],
    verdict:"r",
    example:"9:30 NQ sweeps the daily ERL; two-stage CiC forms (SMT confirms PSP); 5m V-shape CISD leaves a fresh FVG; short on FVG retest targets the opposing daily IRL.",
    donts:["Reversals require a V-shaped displacement — if the CISD looks like consolidation, do not trade that fractal","The two-stage CiC is required — a single-stage confirmation is not enough for a true reversal entry","Don't blindly continuation-trade after price hits a HTF relevant swing — let the new phase hold as a new invalidation","Don't fight the higher timeframe — a LTF reversal that opposes the active HTF cycle is a trap"] },

  { id:"xyj-mmxm-continuation", mentor:"XYJ", mentorKey:"xyj", guideId:"xyj",
    name:"MMXM Continuation (Type 1 / IRL→ERL)",
    session:"NY AM killzone 09:30–11:00 ET", sessionKey:"ny-am",
    htf:"The highest-probability sequence — a true reversal (C2) is established and has expanded away; C3 opens and retraces into a newly formed FVG",
    trigger:"A one-stage CiC (n−1) inside the new HTF gap",
    entry:"On the execution TF (5m/3m) wait for the LTF reversal signature (CISD / V-shape) inside the gap — zero additional CiCs needed",
    stop:"Below the true invalidation — the swing low within the HTF continuation gap",
    target:"The opposing external objective (the internal model draw or failure swings left behind)",
    tfs:"Daily/4H C2 confirmed → 30m/15m C3 gap → 5m/3m execution",
    tools:["MMXM","CiC","CISD","IRL/ERL","continuation gap","equilibrium filter"],
    verdict:"a",
    example:"Wednesday true reversal (C2) confirmed; Thursday C3 opens and retraces to a 30m FVG at equilibrium; one-stage SMT fill at 9:30; 5m V-shape CISD triggers short; targets the opposing failure swings.",
    donts:["Deep retracement kills expansion — if price retraces past the gap equilibrium, the continuation idea is invalidated","Don't blindly continuation-trade if price hits a HTF relevant swing first — let the new phase establish its own invalidation","Gaps must form near the open, not near the candle's high (premium) — wrong gap location = disqualified","Don't enter without an LTF CISD/V-shape inside the gap — the HTF gap alone is not an entry"] },

  { id:"xyj-strength-switch", mentor:"XYJ", mentorKey:"xyj", guideId:"xyj",
    name:"Strength-Switch / Lagging-Asset (\"Ideal Sequence\")",
    session:"NY AM / NY PM killzones", sessionKey:"ny-am",
    htf:"The triad desynchronizes; the leading asset trades deep into the extreme but fails to reverse, entering a new phase (consolidation/retrace)",
    trigger:"The leader prints a Strength Switch PSP (trades into a high but closes as a weak down-close) and leaves a gap; the lagging asset then forms an SMT Fill inside that gap",
    entry:"An LTF CISD/MSS on the lagging asset as it catches up",
    stop:"Below the invalidation of the newly formed swing",
    target:"The SMT break — the exact key level/high the leading asset previously tapped",
    tfs:"4H/1H context → 15m/5m execution",
    tools:["Strength Switch PSP","SMT Fill","lagging asset","CISD","IRL/ERL","Liquidity Dispersal Theory"],
    verdict:"r",
    example:"NQ sweeps the session high but closes as a PSP (Strength Switch); YM (lagging) forms an SMT Fill inside the 15m FVG; long YM CISD targets the same session high NQ tapped.",
    donts:["Don't trade the leader — only trade the lagging asset after the leader prints the Strength Switch PSP and leaves a gap","Deep retracement kills expansion — if the lagging asset retraces past gap equilibrium after the PSP, skip","Stop must sit in the discount of the expanding candle — don't place it in premium (near the candle's high)","Don't fight the higher timeframe — a strength-switch that opposes the active HTF cycle direction is a trap"] },

  { id:"xyj-seek-destroy", mentor:"XYJ", mentorKey:"xyj", guideId:"xyj",
    name:"Seek & Destroy Session",
    session:"London / overnight session (12:00 AM – 6:00 AM ET)", sessionKey:"london",
    htf:"Often the overnight/London session — an asymmetric broadening formation sweeping both highs and lows, price typically high in a daily premium",
    trigger:"After sweeping external liquidity, wait for an aligned HTF open (10:00 / 10:30 AM 90-minute open); the market must print a sequential SMT or two-stage CiC (a PSP) at the engineered high to confirm the local top",
    entry:"On a true CISD — a mechanical closure through the single candle that formed the sequential SMT on a low TF (2m/1m)",
    stop:"Statically above the engineered highs of the manipulation",
    target:"The Logical Liquidity Target (equilibrium) or the engineered overnight lows (often 5.5R+)",
    tfs:"1H overnight context → 15m/5m → 2m/1m execution",
    tools:["Seek & Destroy","PSP","sequential SMT","CISD","broadening formation","continuation"],
    verdict:"a",
    example:"London overnight broadening formation sweeps both BSL and SSL; 10:00 AM HTF open aligns; PSP at the engineered high confirms local top; 1m CISD short targets the overnight lows at 5.5R.",
    donts:["Do NOT wait for an MSS/CISD on the Seek and Destroy — there is no R:R left by then; turtle-soup the swept lows directly","Reversals require a V-shaped displacement — consolidation signatures after the sweep disqualify the entry","Don't enter without an aligned HTF open (10:00/10:30 AM 90-minute) confirming the local top — timing is the gate","Don't fight the higher timeframe — the overnight direction must align with the daily HTF premise"] },

  { id:"xyj-continuation-framework", mentor:"XYJ", mentorKey:"xyj", guideId:"xyj",
    name:"Continuation Framework (qualifying gaps)",
    session:"NY AM killzone 09:30–11:00 ET", sessionKey:"ny-am",
    htf:"A true reversal exists; framing C3/C4 continuations by trading strictly out of gaps",
    trigger:"Qualify the swing via one of three variants — CiC at a gap (SMT Fill), CiC in a gap (PSP closure), or CiC at and in a gap (two-stage SMT + PSP inside it)",
    entry:"Wait for the LTF to shift internal→external inside the HTF gap (CISD)",
    stop:"In the discount of the current expanding candle",
    target:"The opposing side of the dealing range",
    tfs:"Daily/4H context → 30m/15m gap → 5m CISD execution",
    tools:["CiC","CISD","SMT Fill","PSP","continuation gap","Premium/Discount Sequence"],
    verdict:"a",
    example:"True reversal established; C3 retraces to the 15m FVG at equilibrium; SMT Fill (one-stage CiC at the gap) confirms; 5m CISD triggers the short; stop in the discount; targets the opposing dealing range extreme.",
    donts:["Gaps must form near the open of the candle, not near the high (premium) — wrong gap location = disqualified","Stop must sit in the discount of the expanding candle — not in premium","Deep retracement past gap equilibrium invalidates the continuation — expansion does not offer deep retracements","Don't blindly continuation-trade directly after price hits a HTF relevant swing — let the new phase establish its own invalidation level first"] },

  // ─── Daye Mentorship (5) ───────────────────────────────────────────────────

  { id:"dayement-one-shot", mentor:"Daye Mentorship", mentorKey:"dayement", guideId:"dayement",
    name:"Two-Stage Sequential SMT (One Shot One Kill)",
    session:"NY Q3 Sweet Spot 9:00–10:30 AM ET", sessionKey:"ny-am",
    htf:"Stage 1 — Sequential SMT on a higher-TF cycle (e.g. the weekly cycle on the 1H) — e.g. ES takes yesterday's high, NQ fails to",
    trigger:"Stage 2 — drop to the execution TF (15m for the daily cycle) and wait for a Precision Swing Point — the pair's closures contradict",
    entry:"On the True-Open cross (price trades back through the session/day True Open) or the SMT Fill (one asset fills an FVG, the pair fails); execute on the wick of the PSP or the FVG during the mismatch",
    stop:"Fibonacci from the liquidity-run swing low→high; place at 1 standard deviation beyond the extreme (or 0.5 SD for a tight stop)",
    target:"The symmetrical highs/lows (draw on liquidity) or the opposing Sequential SMT; minimum 3R",
    tfs:"1H HTF setup → 15m confirmation → 5m execution",
    tools:["Sequential SMT","Precision Swing Point","True Open","SMT Fill","SD stop","Fibonacci"],
    verdict:"r",
    example:"Weekly 1H Sequential SMT (ES takes yesterday's high, NQ fails); 15m PSP confirms below the 7:30 AM True Open; entry on True-Open cross or FVG; 1 SD stop; targets symmetrical highs at minimum 3R.",
    donts:["'If there's no sequential SMT you basically should not be doing anything at all' — without it, you're just looking at liquidity","A LTF SMT that opposes an active higher-timeframe cycle SMT is fake — need a larger-range SMT to cancel it","Don't enter on clean symmetrical highs/lows — those are exit/draw targets; enter above UNsymmetrical highs","Order blocks and breakers without imbalances are low-probability — disqualify any OB floating in empty space"] },

  { id:"dayement-stage4", mentor:"Daye Mentorship", mentorKey:"dayement", guideId:"dayement",
    name:"The Stage-4 (Advanced 4-Stage) Setup",
    session:"NY Q3 Sweet Spot 9:00–10:30 AM ET", sessionKey:"ny-am",
    htf:"An intricate sequence: (1) HTF Sequential SMT, (2) a mid-TF cycle showing no SMT, (3) a lower-TF Sequential SMT forming a Precision Swing Point",
    trigger:"HTF Sequential SMT → mid-TF no-SMT (pure trend confirmation) → lower-TF Sequential SMT + PSP",
    entry:"On the lower-TF Precision Swing Point or SMT Fill as described in the one-shot sequence",
    stop:"1 SD or 0.5 SD from the manipulation swing",
    target:"Symmetrical highs/lows; minimum 3R",
    tfs:"HTF → mid-TF → LTF execution (3-tier confirmation)",
    tools:["Sequential SMT","Precision Swing Point","True Open","Stacked True Opens","3-stage confirmation"],
    verdict:"r",
    example:"Weekly Sequential SMT aligns; daily mid-cycle shows no SMT (pure trend); 15m PSP confirms below the True Open; enter on SMT Fill; 1 SD stop; targets opposing symmetrical highs at 3R+.",
    donts:["No Sequential SMT at the HTF level = no trade — without it you're just looking at liquidity","If the mid-TF cycle shows an SMT (instead of no-SMT), the 3-stage confirmation is broken — skip","A LTF SMT that opposes the active higher-timeframe cycle SMT is fake — the higher cycle calls the shots","Don't enter on symmetrical highs/lows — those are draw targets; the entry must be at an UNsymmetrical precision swing"] },

  { id:"dayement-monday-expansion", mentor:"Daye Mentorship", mentorKey:"dayement", guideId:"dayement",
    name:"Monday Expansion Model",
    session:"Monday (Q1 of the weekly cycle)", sessionKey:"dow",
    htf:"Sequential SMT forming between the prior week's Friday and the current Monday",
    trigger:"Sequential SMT between Friday's last quarter and Monday's first quarter — Monday becomes an explosive expansion day that forms the high or low of the week",
    entry:"On the True-Open cross or SMT Fill after the Sequential SMT is confirmed below/above the True Week Open (Monday 6:00 PM)",
    stop:"1 SD from the Sequential SMT swing",
    target:"The weekly high or low (the week's draw on liquidity)",
    tfs:"Weekly/Daily context → 1H Monday confirmation → 15m/5m execution",
    tools:["Sequential SMT","True Week Open","Monday Expansion","weekly cycle","Quarterly Theory"],
    verdict:"a",
    example:"Friday Q4 and Monday Q1 form a Sequential SMT (ES makes Friday's low, NQ doesn't); Monday opens above the True Week Open; explosive bullish expansion targets the weekly high.",
    donts:["No Sequential SMT between Friday's last quarter and Monday's first quarter = no Monday Expansion — it's the non-negotiable trigger","A LTF SMT opposing the active higher-timeframe cycle SMT is fake — need a larger-range SMT to cancel it","Don't enter on symmetrical highs/lows — those are the weekly draw targets, not entry points","Order blocks and breakers without surrounding imbalances are low-probability — disqualify OBs in empty space"] },

  { id:"dayement-cpi", mentor:"Daye Mentorship", mentorKey:"dayement", guideId:"dayement",
    name:"CPI Trading Model",
    session:"CPI release day (typically 8:30 AM ET)", sessionKey:"news",
    htf:"CPI direction is set days beforehand: if Sequential SMT forms the Tuesday/Wednesday prior, the CPI release simply expands aggressively in the pre-established SMT direction",
    trigger:"Sequential SMT forms Tuesday/Wednesday prior to the CPI release in the pre-established direction",
    entry:"After the CPI release expands in the Sequential SMT direction, enter on a True-Open cross or SMT Fill on the execution TF",
    stop:"1 SD from the CPI release swing",
    target:"The draw on liquidity established by the prior-week Sequential SMT",
    tfs:"Weekly/Daily pre-CPI setup → 15m/5m execution on release day",
    tools:["Sequential SMT","CPI driver","True Open","news driver","pre-event setup"],
    verdict:"a",
    example:"Tue/Wed Sequential SMT (NQ fails its high while ES confirms) sets bearish direction; CPI Thursday release expands bearishly; entry on True-Open break targets the weekly draw established by the SMT.",
    donts:["No prior-week Sequential SMT (Tue/Wed) = no CPI trade — the release just expands an already-set direction, it doesn't create one","A LTF SMT that opposes the active higher-timeframe cycle SMT is fake — it will not work","Don't trade the CPI spike direction blindly — wait for the True-Open cross or SMT Fill confirming expansion in the pre-established direction","Don't enter on symmetrical highs/lows — those are the draw targets, not the entry"] },

  { id:"dayement-q4-reversal", mentor:"Daye Mentorship", mentorKey:"dayement", guideId:"dayement",
    name:"Q4 Afternoon Reversal (Mentorship)",
    session:"Afternoon session Q4 12:00 PM – 6:00 PM ET", sessionKey:"ny-pm",
    htf:"Q3 expands aggressively, price breaks back below the 1:30 PM Revolving True Open with a Q3↔Q4 Sequential SMT",
    trigger:"Q3 expands aggressively; Q4 Sequential SMT forms (one asset fails to break the Q3 high/low while its correlated pair does); price breaks back below/above the 1:30 PM Revolving True Open",
    entry:"On the break of the Revolving True Open backed by the Q3↔Q4 Sequential SMT, with a PSP or FVG on the execution TF",
    stop:"1 SD from the Q3 high/low Sequential SMT swing",
    target:"The initial swing low after the SMT, or the daily dealing range equilibrium",
    tfs:"Daily cycle (15m) → 90-minute Q4 cycle (5m)",
    tools:["Revolving True Open","Q3/Q4 Sequential SMT","Quarterly Theory","PSP","FVG"],
    verdict:"a",
    example:"NY Q3 bullishly expands; at 1:30 PM NASDAQ pushes to new Q3 high but S&P fails (Q4 Sequential SMT); price breaks below the Revolving True Open; short on FVG targets the daily equilibrium.",
    donts:["No Q3↔Q4 Sequential SMT = no afternoon reversal — without it you're just fading a random Q4 move","A LTF SMT opposing the active higher-timeframe cycle SMT is fake — the higher cycle calls the shots","Don't enter before price breaks back through the 1:30 PM Revolving True Open — that break is the required confirmation","Don't enter on symmetrical highs/lows — those are draw targets; use a PSP or FVG for the actual entry"] }

];
